name: Ping Website

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping my website
        run: |
          for i in {1..5}; do
            curl -s https://adzu-chat-frontend.vercel.app/ && break || sleep 10;
          done
